/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const VitalSource = IDL.Variant({
  'sensor' : IDL.Null,
  'manual' : IDL.Null,
});
export const Vital = IDL.Record({
  'id' : IDL.Nat,
  'bmi' : IDL.Opt(IDL.Float64),
  'weight' : IDL.Opt(IDL.Float64),
  'source' : VitalSource,
  'patientId' : IDL.Principal,
  'temperature' : IDL.Opt(IDL.Float64),
  'createdAt' : IDL.Int,
  'spo2' : IDL.Opt(IDL.Nat),
  'recordedAt' : IDL.Int,
  'systolicBP' : IDL.Opt(IDL.Nat),
  'bloodSugar' : IDL.Opt(IDL.Float64),
  'diastolicBP' : IDL.Opt(IDL.Nat),
  'heartRate' : IDL.Opt(IDL.Nat),
});
export const VitalsError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'deviceInactive' : IDL.Null,
  'invalidToken' : IDL.Null,
  'deviceNotFound' : IDL.Null,
  'invalidReading' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : Vital, 'err' : VitalsError });
export const Id = IDL.Nat;
export const MedicalHistory = IDL.Record({
  'id' : Id,
  'patientId' : IDL.Principal,
  'date' : IDL.Int,
  'createdBy' : IDL.Principal,
  'treatment' : IDL.Text,
  'diagnosis' : IDL.Text,
  'notes' : IDL.Text,
  'condition' : IDL.Text,
});
export const Role = IDL.Variant({ 'patient' : IDL.Null, 'doctor' : IDL.Null });
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'role' : Role,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DoctorPatientAssignment = IDL.Record({
  'id' : Id,
  'doctorId' : IDL.Principal,
  'assignedAt' : IDL.Int,
  'patientId' : IDL.Principal,
});
export const AppointmentStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : Id,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Principal,
  'patientId' : IDL.Principal,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'notes' : IDL.Text,
  'reason' : IDL.Text,
});
export const ConsultationStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const Consultation = IDL.Record({
  'id' : Id,
  'status' : ConsultationStatus,
  'doctorId' : IDL.Principal,
  'patientId' : IDL.Principal,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'diagnosis' : IDL.Text,
  'notes' : IDL.Text,
  'reason' : IDL.Text,
});
export const NotificationKind = IDL.Variant({
  'appointment' : IDL.Null,
  'prescription' : IDL.Null,
  'vital' : IDL.Null,
  'device' : IDL.Null,
  'medicalHistory' : IDL.Null,
  'systemNotification' : IDL.Null,
  'consultation' : IDL.Null,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'kind' : NotificationKind,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const Medicine = IDL.Record({
  'id' : Id,
  'duration' : IDL.Text,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'frequency' : IDL.Text,
});
export const PrescriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Prescription = IDL.Record({
  'id' : Id,
  'status' : PrescriptionStatus,
  'doctorId' : IDL.Principal,
  'patientId' : IDL.Principal,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'instructions' : IDL.Text,
  'medicines' : IDL.Vec(Medicine),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DoctorProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'contact' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'specialization' : IDL.Text,
  'licenseNumber' : IDL.Text,
});
export const BloodGroup = IDL.Variant({
  'aNegative' : IDL.Null,
  'oPositive' : IDL.Null,
  'abPositive' : IDL.Null,
  'notSpecified' : IDL.Null,
  'bPositive' : IDL.Null,
  'aPositive' : IDL.Null,
  'oNegative' : IDL.Null,
  'abNegative' : IDL.Null,
  'bNegative' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const PatientProfile = IDL.Record({
  'age' : IDL.Nat,
  'contact' : IDL.Text,
  'heightCm' : IDL.Opt(IDL.Float64),
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'emergencyContact' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'weightKg' : IDL.Opt(IDL.Float64),
  'bloodGroup' : BloodGroup,
  'address' : IDL.Text,
  'gender' : Gender,
});
export const DeviceStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Device = IDL.Record({
  'id' : IDL.Nat,
  'status' : DeviceStatus,
  'deviceTokenHash' : IDL.Vec(IDL.Nat8),
  'lastSeenAt' : IDL.Opt(IDL.Int),
  'patientId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'deviceName' : IDL.Text,
  'deviceType' : IDL.Text,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Opt(Device),
  'err' : VitalsError,
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Opt(Vital),
  'err' : VitalsError,
});
export const TimeRange = IDL.Variant({
  'd7' : IDL.Null,
  'm3' : IDL.Null,
  'm6' : IDL.Null,
  'y1' : IDL.Null,
  'd30' : IDL.Null,
  'h24' : IDL.Null,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(Vital),
  'err' : VitalsError,
});
export const Result = IDL.Variant({ 'ok' : Device, 'err' : VitalsError });

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_5], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addManualVital' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Int,
      ],
      [Result_1],
      [],
    ),
  'addMedicalHistory' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [MedicalHistory],
      [],
    ),
  'assignCallerRole' : IDL.Func([Role], [User], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPatient' : IDL.Func([IDL.Principal], [DoctorPatientAssignment], []),
  'bookAppointment' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Text, IDL.Text, IDL.Text],
      [Appointment],
      [],
    ),
  'cancelAppointment' : IDL.Func([Id], [IDL.Bool], []),
  'createConsultation' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Text, IDL.Text, IDL.Text],
      [Consultation],
      [],
    ),
  'createNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, NotificationKind],
      [Notification],
      [],
    ),
  'createPrescription' : IDL.Func(
      [IDL.Principal, IDL.Vec(Medicine), IDL.Text, IDL.Int],
      [Prescription],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerDoctorProfile' : IDL.Func([], [IDL.Opt(DoctorProfile)], ['query']),
  'getCallerPatientProfile' : IDL.Func(
      [],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getCallerRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsultation' : IDL.Func([Id], [IDL.Opt(Consultation)], ['query']),
  'getDeviceStatus' : IDL.Func([IDL.Principal], [Result_4], ['query']),
  'getLatestVitals' : IDL.Func([IDL.Principal], [Result_3], ['query']),
  'getMedicalHistory' : IDL.Func([Id], [IDL.Opt(MedicalHistory)], ['query']),
  'getPrescription' : IDL.Func([Id], [IDL.Opt(Prescription)], ['query']),
  'getVitalsHistory' : IDL.Func(
      [IDL.Principal, TimeRange],
      [Result_2],
      ['query'],
    ),
  'ingestVitals' : IDL.Func(
      [
        IDL.Vec(IDL.Nat8),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Float64),
        IDL.Int,
      ],
      [Result_1],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAppointments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'listAssignedPatients' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DoctorPatientAssignment)],
      ['query'],
    ),
  'listConsultations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Consultation)],
      ['query'],
    ),
  'listMedicalHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MedicalHistory)],
      ['query'],
    ),
  'listMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listPrescriptions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'manageAppointment' : IDL.Func([Id, AppointmentStatus], [IDL.Bool], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'registerDevice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [Result],
      [],
    ),
  'saveCallerDoctorProfile' : IDL.Func([DoctorProfile], [DoctorProfile], []),
  'saveCallerPatientProfile' : IDL.Func([PatientProfile], [PatientProfile], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'unreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const VitalSource = IDL.Variant({ 'sensor' : IDL.Null, 'manual' : IDL.Null });
  const Vital = IDL.Record({
    'id' : IDL.Nat,
    'bmi' : IDL.Opt(IDL.Float64),
    'weight' : IDL.Opt(IDL.Float64),
    'source' : VitalSource,
    'patientId' : IDL.Principal,
    'temperature' : IDL.Opt(IDL.Float64),
    'createdAt' : IDL.Int,
    'spo2' : IDL.Opt(IDL.Nat),
    'recordedAt' : IDL.Int,
    'systolicBP' : IDL.Opt(IDL.Nat),
    'bloodSugar' : IDL.Opt(IDL.Float64),
    'diastolicBP' : IDL.Opt(IDL.Nat),
    'heartRate' : IDL.Opt(IDL.Nat),
  });
  const VitalsError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'deviceInactive' : IDL.Null,
    'invalidToken' : IDL.Null,
    'deviceNotFound' : IDL.Null,
    'invalidReading' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : Vital, 'err' : VitalsError });
  const Id = IDL.Nat;
  const MedicalHistory = IDL.Record({
    'id' : Id,
    'patientId' : IDL.Principal,
    'date' : IDL.Int,
    'createdBy' : IDL.Principal,
    'treatment' : IDL.Text,
    'diagnosis' : IDL.Text,
    'notes' : IDL.Text,
    'condition' : IDL.Text,
  });
  const Role = IDL.Variant({ 'patient' : IDL.Null, 'doctor' : IDL.Null });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'role' : Role,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DoctorPatientAssignment = IDL.Record({
    'id' : Id,
    'doctorId' : IDL.Principal,
    'assignedAt' : IDL.Int,
    'patientId' : IDL.Principal,
  });
  const AppointmentStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : Id,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Principal,
    'patientId' : IDL.Principal,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'notes' : IDL.Text,
    'reason' : IDL.Text,
  });
  const ConsultationStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
  });
  const Consultation = IDL.Record({
    'id' : Id,
    'status' : ConsultationStatus,
    'doctorId' : IDL.Principal,
    'patientId' : IDL.Principal,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'diagnosis' : IDL.Text,
    'notes' : IDL.Text,
    'reason' : IDL.Text,
  });
  const NotificationKind = IDL.Variant({
    'appointment' : IDL.Null,
    'prescription' : IDL.Null,
    'vital' : IDL.Null,
    'device' : IDL.Null,
    'medicalHistory' : IDL.Null,
    'systemNotification' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'kind' : NotificationKind,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Medicine = IDL.Record({
    'id' : Id,
    'duration' : IDL.Text,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const PrescriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Prescription = IDL.Record({
    'id' : Id,
    'status' : PrescriptionStatus,
    'doctorId' : IDL.Principal,
    'patientId' : IDL.Principal,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'instructions' : IDL.Text,
    'medicines' : IDL.Vec(Medicine),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DoctorProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'contact' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'specialization' : IDL.Text,
    'licenseNumber' : IDL.Text,
  });
  const BloodGroup = IDL.Variant({
    'aNegative' : IDL.Null,
    'oPositive' : IDL.Null,
    'abPositive' : IDL.Null,
    'notSpecified' : IDL.Null,
    'bPositive' : IDL.Null,
    'aPositive' : IDL.Null,
    'oNegative' : IDL.Null,
    'abNegative' : IDL.Null,
    'bNegative' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const PatientProfile = IDL.Record({
    'age' : IDL.Nat,
    'contact' : IDL.Text,
    'heightCm' : IDL.Opt(IDL.Float64),
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'emergencyContact' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'weightKg' : IDL.Opt(IDL.Float64),
    'bloodGroup' : BloodGroup,
    'address' : IDL.Text,
    'gender' : Gender,
  });
  const DeviceStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Device = IDL.Record({
    'id' : IDL.Nat,
    'status' : DeviceStatus,
    'deviceTokenHash' : IDL.Vec(IDL.Nat8),
    'lastSeenAt' : IDL.Opt(IDL.Int),
    'patientId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'deviceName' : IDL.Text,
    'deviceType' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Opt(Device), 'err' : VitalsError });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Opt(Vital), 'err' : VitalsError });
  const TimeRange = IDL.Variant({
    'd7' : IDL.Null,
    'm3' : IDL.Null,
    'm6' : IDL.Null,
    'y1' : IDL.Null,
    'd30' : IDL.Null,
    'h24' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Vec(Vital), 'err' : VitalsError });
  const Result = IDL.Variant({ 'ok' : Device, 'err' : VitalsError });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_5], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addManualVital' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Int,
        ],
        [Result_1],
        [],
      ),
    'addMedicalHistory' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [MedicalHistory],
        [],
      ),
    'assignCallerRole' : IDL.Func([Role], [User], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPatient' : IDL.Func([IDL.Principal], [DoctorPatientAssignment], []),
    'bookAppointment' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Text, IDL.Text, IDL.Text],
        [Appointment],
        [],
      ),
    'cancelAppointment' : IDL.Func([Id], [IDL.Bool], []),
    'createConsultation' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Text, IDL.Text, IDL.Text],
        [Consultation],
        [],
      ),
    'createNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, NotificationKind],
        [Notification],
        [],
      ),
    'createPrescription' : IDL.Func(
        [IDL.Principal, IDL.Vec(Medicine), IDL.Text, IDL.Int],
        [Prescription],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerDoctorProfile' : IDL.Func(
        [],
        [IDL.Opt(DoctorProfile)],
        ['query'],
      ),
    'getCallerPatientProfile' : IDL.Func(
        [],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsultation' : IDL.Func([Id], [IDL.Opt(Consultation)], ['query']),
    'getDeviceStatus' : IDL.Func([IDL.Principal], [Result_4], ['query']),
    'getLatestVitals' : IDL.Func([IDL.Principal], [Result_3], ['query']),
    'getMedicalHistory' : IDL.Func([Id], [IDL.Opt(MedicalHistory)], ['query']),
    'getPrescription' : IDL.Func([Id], [IDL.Opt(Prescription)], ['query']),
    'getVitalsHistory' : IDL.Func(
        [IDL.Principal, TimeRange],
        [Result_2],
        ['query'],
      ),
    'ingestVitals' : IDL.Func(
        [
          IDL.Vec(IDL.Nat8),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Float64),
          IDL.Int,
        ],
        [Result_1],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAppointments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'listAssignedPatients' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DoctorPatientAssignment)],
        ['query'],
      ),
    'listConsultations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Consultation)],
        ['query'],
      ),
    'listMedicalHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MedicalHistory)],
        ['query'],
      ),
    'listMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listPrescriptions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'manageAppointment' : IDL.Func([Id, AppointmentStatus], [IDL.Bool], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'registerDevice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
    'saveCallerDoctorProfile' : IDL.Func([DoctorProfile], [DoctorProfile], []),
    'saveCallerPatientProfile' : IDL.Func(
        [PatientProfile],
        [PatientProfile],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'unreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };