/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : Id,
  'status' : AppointmentStatus,
  'doctorId' : Principal,
  'patientId' : Principal,
  'date' : bigint,
  'createdAt' : bigint,
  'time' : string,
  'notes' : string,
  'reason' : string,
}
export type AppointmentStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type BloodGroup = { 'aNegative' : null } |
  { 'oPositive' : null } |
  { 'abPositive' : null } |
  { 'notSpecified' : null } |
  { 'bPositive' : null } |
  { 'aPositive' : null } |
  { 'oNegative' : null } |
  { 'abNegative' : null } |
  { 'bNegative' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Consultation {
  'id' : Id,
  'status' : ConsultationStatus,
  'doctorId' : Principal,
  'patientId' : Principal,
  'date' : bigint,
  'createdAt' : bigint,
  'diagnosis' : string,
  'notes' : string,
  'reason' : string,
}
export type ConsultationStatus = { 'closed' : null } |
  { 'open' : null };
export interface Device {
  'id' : bigint,
  'status' : DeviceStatus,
  'deviceTokenHash' : Uint8Array,
  'lastSeenAt' : [] | [bigint],
  'patientId' : Principal,
  'createdAt' : bigint,
  'deviceName' : string,
  'deviceType' : string,
}
export type DeviceStatus = { 'active' : null } |
  { 'inactive' : null };
export interface DoctorPatientAssignment {
  'id' : Id,
  'doctorId' : Principal,
  'assignedAt' : bigint,
  'patientId' : Principal,
}
export interface DoctorProfile {
  'bio' : [] | [string],
  'contact' : string,
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
  'updatedAt' : bigint,
  'specialization' : string,
  'licenseNumber' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type Id = bigint;
export interface MedicalHistory {
  'id' : Id,
  'patientId' : Principal,
  'date' : bigint,
  'createdBy' : Principal,
  'treatment' : string,
  'diagnosis' : string,
  'notes' : string,
  'condition' : string,
}
export interface Medicine {
  'id' : Id,
  'duration' : string,
  'dosage' : string,
  'name' : string,
  'frequency' : string,
}
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'userId' : Principal,
  'kind' : NotificationKind,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
}
export type NotificationId = bigint;
export type NotificationKind = { 'appointment' : null } |
  { 'prescription' : null } |
  { 'vital' : null } |
  { 'device' : null } |
  { 'medicalHistory' : null } |
  { 'systemNotification' : null } |
  { 'consultation' : null };
export interface PatientProfile {
  'age' : bigint,
  'contact' : string,
  'heightCm' : [] | [number],
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'emergencyContact' : [] | [string],
  'updatedAt' : bigint,
  'weightKg' : [] | [number],
  'bloodGroup' : BloodGroup,
  'address' : string,
  'gender' : Gender,
}
export interface Prescription {
  'id' : Id,
  'status' : PrescriptionStatus,
  'doctorId' : Principal,
  'patientId' : Principal,
  'date' : bigint,
  'createdAt' : bigint,
  'instructions' : string,
  'medicines' : Array<Medicine>,
}
export type PrescriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type Result = { 'ok' : Device } |
  { 'err' : VitalsError };
export type Result_1 = { 'ok' : Vital } |
  { 'err' : VitalsError };
export type Result_2 = { 'ok' : Array<Vital> } |
  { 'err' : VitalsError };
export type Result_3 = { 'ok' : [] | [Vital] } |
  { 'err' : VitalsError };
export type Result_4 = { 'ok' : [] | [Device] } |
  { 'err' : VitalsError };
export type Result_5 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Role = { 'patient' : null } |
  { 'doctor' : null };
export type TimeRange = { 'd7' : null } |
  { 'm3' : null } |
  { 'm6' : null } |
  { 'y1' : null } |
  { 'd30' : null } |
  { 'h24' : null };
export interface User {
  'principal' : Principal,
  'createdAt' : bigint,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface Vital {
  'id' : bigint,
  'bmi' : [] | [number],
  'weight' : [] | [number],
  'source' : VitalSource,
  'patientId' : Principal,
  'temperature' : [] | [number],
  'createdAt' : bigint,
  'spo2' : [] | [bigint],
  'recordedAt' : bigint,
  'systolicBP' : [] | [bigint],
  'bloodSugar' : [] | [number],
  'diastolicBP' : [] | [bigint],
  'heartRate' : [] | [bigint],
}
export type VitalSource = { 'sensor' : null } |
  { 'manual' : null };
export type VitalsError = { 'notAuthorized' : null } |
  { 'deviceInactive' : null } |
  { 'invalidToken' : null } |
  { 'deviceNotFound' : null } |
  { 'invalidReading' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_5>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addManualVital' : ActorMethod<
    [
      [] | [bigint],
      [] | [bigint],
      [] | [number],
      [] | [bigint],
      [] | [bigint],
      [] | [number],
      [] | [number],
      [] | [number],
      bigint,
    ],
    Result_1
  >,
  'addMedicalHistory' : ActorMethod<
    [Principal, string, string, string, bigint, string],
    MedicalHistory
  >,
  'assignCallerRole' : ActorMethod<[Role], User>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPatient' : ActorMethod<[Principal], DoctorPatientAssignment>,
  'bookAppointment' : ActorMethod<
    [Principal, bigint, string, string, string],
    Appointment
  >,
  'cancelAppointment' : ActorMethod<[Id], boolean>,
  'createConsultation' : ActorMethod<
    [Principal, bigint, string, string, string],
    Consultation
  >,
  'createNotification' : ActorMethod<
    [Principal, string, string, NotificationKind],
    Notification
  >,
  'createPrescription' : ActorMethod<
    [Principal, Array<Medicine>, string, bigint],
    Prescription
  >,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerDoctorProfile' : ActorMethod<[], [] | [DoctorProfile]>,
  'getCallerPatientProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getCallerRole' : ActorMethod<[], [] | [Role]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsultation' : ActorMethod<[Id], [] | [Consultation]>,
  'getDeviceStatus' : ActorMethod<[Principal], Result_4>,
  'getLatestVitals' : ActorMethod<[Principal], Result_3>,
  'getMedicalHistory' : ActorMethod<[Id], [] | [MedicalHistory]>,
  'getPrescription' : ActorMethod<[Id], [] | [Prescription]>,
  'getVitalsHistory' : ActorMethod<[Principal, TimeRange], Result_2>,
  'ingestVitals' : ActorMethod<
    [Uint8Array, [] | [bigint], [] | [bigint], [] | [number], bigint],
    Result_1
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAppointments' : ActorMethod<[Principal], Array<Appointment>>,
  'listAssignedPatients' : ActorMethod<
    [Principal],
    Array<DoctorPatientAssignment>
  >,
  'listConsultations' : ActorMethod<[Principal], Array<Consultation>>,
  'listMedicalHistory' : ActorMethod<[Principal], Array<MedicalHistory>>,
  'listMyNotifications' : ActorMethod<[], Array<Notification>>,
  'listPrescriptions' : ActorMethod<[Principal], Array<Prescription>>,
  'manageAppointment' : ActorMethod<[Id, AppointmentStatus], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[NotificationId], boolean>,
  'registerDevice' : ActorMethod<[string, string, Uint8Array], Result>,
  'saveCallerDoctorProfile' : ActorMethod<[DoctorProfile], DoctorProfile>,
  'saveCallerPatientProfile' : ActorMethod<[PatientProfile], PatientProfile>,
  'schema' : ActorMethod<[], string>,
  'unreadNotificationCount' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];