/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Result_2 = {
    __kind__: "ok";
    ok: Array<Vital>;
} | {
    __kind__: "err";
    err: VitalsError;
};
export interface DoctorProfile {
    bio?: string;
    contact: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    email?: string;
    updatedAt: bigint;
    specialization: string;
    licenseNumber: string;
}
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Vital {
    id: bigint;
    bmi?: number;
    weight?: number;
    source: VitalSource;
    patientId: Principal;
    temperature?: number;
    createdAt: bigint;
    spo2?: bigint;
    recordedAt: bigint;
    systolicBP?: bigint;
    bloodSugar?: number;
    diastolicBP?: bigint;
    heartRate?: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: Vital;
} | {
    __kind__: "err";
    err: VitalsError;
};
export type Result_5 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_4 = {
    __kind__: "ok";
    ok: Device | null;
} | {
    __kind__: "err";
    err: VitalsError;
};
export interface Cell {
    value: Value;
    name: string;
}
export interface PatientProfile {
    age: bigint;
    contact: string;
    heightCm?: number;
    userId: Principal;
    name: string;
    createdAt: bigint;
    emergencyContact?: string;
    updatedAt: bigint;
    weightKg?: number;
    bloodGroup: BloodGroup;
    address: string;
    gender: Gender;
}
export interface Medicine {
    id: Id;
    duration: string;
    dosage: string;
    name: string;
    frequency: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Consultation {
    id: Id;
    status: ConsultationStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    diagnosis: string;
    notes: string;
    reason: string;
}
export interface User {
    principal: Principal;
    createdAt: bigint;
    role: Role;
}
export interface MedicalHistory {
    id: Id;
    patientId: Principal;
    date: bigint;
    createdBy: Principal;
    treatment: string;
    diagnosis: string;
    notes: string;
    condition: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Device {
    id: bigint;
    status: DeviceStatus;
    deviceTokenHash: Uint8Array;
    lastSeenAt?: bigint;
    patientId: Principal;
    createdAt: bigint;
    deviceName: string;
    deviceType: string;
}
export interface DoctorPatientAssignment {
    id: Id;
    doctorId: Principal;
    assignedAt: bigint;
    patientId: Principal;
}
export type Result = {
    __kind__: "ok";
    ok: Device;
} | {
    __kind__: "err";
    err: VitalsError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Vital | null;
} | {
    __kind__: "err";
    err: VitalsError;
};
export type NotificationId = bigint;
export interface Notification {
    id: NotificationId;
    title: string;
    userId: Principal;
    kind: NotificationKind;
    createdAt: bigint;
    isRead: boolean;
    message: string;
}
export type Id = bigint;
export interface Appointment {
    id: Id;
    status: AppointmentStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    time: string;
    notes: string;
    reason: string;
}
export interface Prescription {
    id: Id;
    status: PrescriptionStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    instructions: string;
    medicines: Array<Medicine>;
}
export enum AppointmentStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum BloodGroup {
    aNegative = "aNegative",
    oPositive = "oPositive",
    abPositive = "abPositive",
    notSpecified = "notSpecified",
    bPositive = "bPositive",
    aPositive = "aPositive",
    oNegative = "oNegative",
    abNegative = "abNegative",
    bNegative = "bNegative"
}
export enum ConsultationStatus {
    closed = "closed",
    open = "open"
}
export enum DeviceStatus {
    active = "active",
    inactive = "inactive"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum NotificationKind {
    appointment = "appointment",
    prescription = "prescription",
    vital = "vital",
    device = "device",
    medicalHistory = "medicalHistory",
    systemNotification = "systemNotification",
    consultation = "consultation"
}
export enum PrescriptionStatus {
    active = "active",
    cancelled = "cancelled",
    completed = "completed"
}
export enum Role {
    patient = "patient",
    doctor = "doctor"
}
export enum TimeRange {
    d7 = "d7",
    m3 = "m3",
    m6 = "m6",
    y1 = "y1",
    d30 = "d30",
    h24 = "h24"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VitalSource {
    sensor = "sensor",
    manual = "manual"
}
export enum VitalsError {
    notAuthorized = "notAuthorized",
    deviceInactive = "deviceInactive",
    invalidToken = "invalidToken",
    deviceNotFound = "deviceNotFound",
    invalidReading = "invalidReading"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_5>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addManualVital(heartRate: bigint | null, spo2: bigint | null, temperature: number | null, systolicBP: bigint | null, diastolicBP: bigint | null, bloodSugar: number | null, weight: number | null, bmi: number | null, recordedAt: bigint): Promise<Result_1>;
    addMedicalHistory(patientId: Principal, condition: string, diagnosis: string, treatment: string, date: bigint, notes: string): Promise<MedicalHistory>;
    assignCallerRole(role: Role): Promise<User>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignPatient(patientId: Principal): Promise<DoctorPatientAssignment>;
    bookAppointment(doctorId: Principal, date: bigint, time: string, reason: string, notes: string): Promise<Appointment>;
    cancelAppointment(id: Id): Promise<boolean>;
    createConsultation(patientId: Principal, date: bigint, reason: string, diagnosis: string, notes: string): Promise<Consultation>;
    createNotification(userId: Principal, title: string, message: string, kind: NotificationKind): Promise<Notification>;
    createPrescription(patientId: Principal, medicines: Array<Medicine>, instructions: string, date: bigint): Promise<Prescription>;
    execute(qJson: string): Promise<Result__1>;
    getApiDoc(): Promise<string>;
    getCallerDoctorProfile(): Promise<DoctorProfile | null>;
    getCallerPatientProfile(): Promise<PatientProfile | null>;
    getCallerRole(): Promise<Role | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConsultation(id: Id): Promise<Consultation | null>;
    getDeviceStatus(patientId: Principal): Promise<Result_4>;
    getLatestVitals(patientId: Principal): Promise<Result_3>;
    getMedicalHistory(id: Id): Promise<MedicalHistory | null>;
    getPrescription(id: Id): Promise<Prescription | null>;
    getVitalsHistory(patientId: Principal, range: TimeRange): Promise<Result_2>;
    ingestVitals(deviceToken: Uint8Array, heartRate: bigint | null, spo2: bigint | null, temperature: number | null, recordedAt: bigint): Promise<Result_1>;
    isCallerAdmin(): Promise<boolean>;
    listAppointments(patientId: Principal): Promise<Array<Appointment>>;
    listAssignedPatients(doctorId: Principal): Promise<Array<DoctorPatientAssignment>>;
    listConsultations(patientId: Principal): Promise<Array<Consultation>>;
    listMedicalHistory(patientId: Principal): Promise<Array<MedicalHistory>>;
    listMyNotifications(): Promise<Array<Notification>>;
    listPrescriptions(patientId: Principal): Promise<Array<Prescription>>;
    manageAppointment(id: Id, status: AppointmentStatus): Promise<boolean>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationAsRead(notificationId: NotificationId): Promise<boolean>;
    registerDevice(deviceName: string, deviceType: string, deviceToken: Uint8Array): Promise<Result>;
    saveCallerDoctorProfile(profile: DoctorProfile): Promise<DoctorProfile>;
    saveCallerPatientProfile(profile: PatientProfile): Promise<PatientProfile>;
    schema(): Promise<string>;
    unreadNotificationCount(): Promise<bigint>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, BloodGroup as _BloodGroup, Cell as _Cell, Consultation as _Consultation, ConsultationStatus as _ConsultationStatus, Device as _Device, DeviceStatus as _DeviceStatus, DoctorProfile as _DoctorProfile, Error as _Error, Gender as _Gender, Id as _Id, MedicalHistory as _MedicalHistory, Medicine as _Medicine, Notification as _Notification, NotificationId as _NotificationId, NotificationKind as _NotificationKind, PatientProfile as _PatientProfile, Prescription as _Prescription, PrescriptionStatus as _PrescriptionStatus, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result__1 as _Result__1, Role as _Role, TimeRange as _TimeRange, User as _User, UserRole as _UserRole, Value as _Value, Vital as _Vital, VitalSource as _VitalSource, VitalsError as _VitalsError } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_5_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_5_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addManualVital(arg0: bigint | null, arg1: bigint | null, arg2: number | null, arg3: bigint | null, arg4: bigint | null, arg5: number | null, arg6: number | null, arg7: number | null, arg8: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addManualVital(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg7), arg8);
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addManualVital(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg7), arg8);
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMedicalHistory(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<MedicalHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicalHistory(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicalHistory(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerRole(arg0: Role): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerRole(to_candid_Role_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerRole(to_candid_Role_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignPatient(arg0: Principal): Promise<DoctorPatientAssignment> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPatient(arg0);
            return result;
        }
    }
    async bookAppointment(arg0: Principal, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Appointment_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Appointment_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelAppointment(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async createConsultation(arg0: Principal, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<Consultation> {
        if (this.processError) {
            try {
                const result = await this.actor.createConsultation(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Consultation_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConsultation(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Consultation_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotification(arg0: Principal, arg1: string, arg2: string, arg3: NotificationKind): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2, to_candid_NotificationKind_n33(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Notification_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2, to_candid_NotificationKind_n33(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Notification_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPrescription(arg0: Principal, arg1: Array<Medicine>, arg2: string, arg3: bigint): Promise<Prescription> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrescription(arg0, arg1, arg2, arg3);
                return from_candid_Prescription_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrescription(arg0, arg1, arg2, arg3);
            return from_candid_Prescription_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerDoctorProfile(): Promise<DoctorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDoctorProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDoctorProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPatientProfile(): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPatientProfile();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPatientProfile();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerRole(): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConsultation(arg0: Id): Promise<Consultation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsultation(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsultation(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeviceStatus(arg0: Principal): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceStatus(arg0);
                return from_candid_Result_4_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceStatus(arg0);
            return from_candid_Result_4_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestVitals(arg0: Principal): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestVitals(arg0);
                return from_candid_Result_3_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestVitals(arg0);
            return from_candid_Result_3_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicalHistory(arg0: Id): Promise<MedicalHistory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalHistory(arg0);
                return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalHistory(arg0);
            return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescription(arg0: Id): Promise<Prescription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescription(arg0);
                return from_candid_opt_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescription(arg0);
            return from_candid_opt_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVitalsHistory(arg0: Principal, arg1: TimeRange): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getVitalsHistory(arg0, to_candid_TimeRange_n79(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_2_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVitalsHistory(arg0, to_candid_TimeRange_n79(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_2_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async ingestVitals(arg0: Uint8Array, arg1: bigint | null, arg2: bigint | null, arg3: number | null, arg4: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.ingestVitals(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ingestVitals(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAppointments(arg0: Principal): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointments(arg0);
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointments(arg0);
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssignedPatients(arg0: Principal): Promise<Array<DoctorPatientAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssignedPatients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssignedPatients(arg0);
            return result;
        }
    }
    async listConsultations(arg0: Principal): Promise<Array<Consultation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConsultations(arg0);
                return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConsultations(arg0);
            return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMedicalHistory(arg0: Principal): Promise<Array<MedicalHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMedicalHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMedicalHistory(arg0);
            return result;
        }
    }
    async listMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyNotifications();
                return from_candid_vec_n86(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyNotifications();
            return from_candid_vec_n86(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPrescriptions(arg0: Principal): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPrescriptions(arg0);
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPrescriptions(arg0);
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async manageAppointment(arg0: Id, arg1: AppointmentStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.manageAppointment(arg0, to_candid_AppointmentStatus_n88(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.manageAppointment(arg0, to_candid_AppointmentStatus_n88(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationAsRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async registerDevice(arg0: string, arg1: string, arg2: Uint8Array): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDevice(arg0, arg1, arg2);
                return from_candid_Result_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDevice(arg0, arg1, arg2);
            return from_candid_Result_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerDoctorProfile(arg0: DoctorProfile): Promise<DoctorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerDoctorProfile(to_candid_DoctorProfile_n92(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DoctorProfile_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerDoctorProfile(to_candid_DoctorProfile_n92(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DoctorProfile_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerPatientProfile(arg0: PatientProfile): Promise<PatientProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerPatientProfile(to_candid_PatientProfile_n94(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PatientProfile_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerPatientProfile(to_candid_PatientProfile_n94(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PatientProfile_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async unreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.unreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unreadNotificationCount();
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_BloodGroup_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ConsultationStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationStatus): ConsultationStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Consultation_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Consultation): Consultation {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_DeviceStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviceStatus): DeviceStatus {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_Device_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Device): Device {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_DoctorProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoctorProfile): DoctorProfile {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationKind_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationKind): NotificationKind {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PatientProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientProfile): PatientProfile {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_PrescriptionStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrescriptionStatus): PrescriptionStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Prescription_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prescription): Prescription {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n82(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n91(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_User_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_VitalSource_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VitalSource): VitalSource {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Vital_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vital): Vital {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_VitalsError_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VitalsError): VitalsError {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DoctorProfile]): DoctorProfile | null {
    return value.length === 0 ? null : from_candid_DoctorProfile_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientProfile]): PatientProfile | null {
    return value.length === 0 ? null : from_candid_PatientProfile_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Consultation]): Consultation | null {
    return value.length === 0 ? null : from_candid_Consultation_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Device]): Device | null {
    return value.length === 0 ? null : from_candid_Device_n69(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vital]): Vital | null {
    return value.length === 0 ? null : from_candid_Vital_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MedicalHistory]): MedicalHistory | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Prescription]): Prescription | null {
    return value.length === 0 ? null : from_candid_Prescription_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bmi: [] | [number];
    weight: [] | [number];
    source: _VitalSource;
    patientId: Principal;
    temperature: [] | [number];
    createdAt: bigint;
    spo2: [] | [bigint];
    recordedAt: bigint;
    systolicBP: [] | [bigint];
    bloodSugar: [] | [number];
    diastolicBP: [] | [bigint];
    heartRate: [] | [bigint];
}): {
    id: bigint;
    bmi?: number;
    weight?: number;
    source: VitalSource;
    patientId: Principal;
    temperature?: number;
    createdAt: bigint;
    spo2?: bigint;
    recordedAt: bigint;
    systolicBP?: bigint;
    bloodSugar?: number;
    diastolicBP?: bigint;
    heartRate?: bigint;
} {
    return {
        id: value.id,
        bmi: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.bmi)),
        weight: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.weight)),
        source: from_candid_VitalSource_n12(_uploadFile, _downloadFile, value.source),
        patientId: value.patientId,
        temperature: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.temperature)),
        createdAt: value.createdAt,
        spo2: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.spo2)),
        recordedAt: value.recordedAt,
        systolicBP: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.systolicBP)),
        bloodSugar: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.bloodSugar)),
        diastolicBP: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.diastolicBP)),
        heartRate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.heartRate))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    createdAt: bigint;
    role: _Role;
}): {
    principal: Principal;
    createdAt: bigint;
    role: Role;
} {
    return {
        principal: value.principal,
        createdAt: value.createdAt,
        role: from_candid_Role_n21(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _AppointmentStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    time: string;
    notes: string;
    reason: string;
}): {
    id: Id;
    status: AppointmentStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    time: string;
    notes: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n27(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        createdAt: value.createdAt,
        time: value.time,
        notes: value.notes,
        reason: value.reason
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _ConsultationStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    diagnosis: string;
    notes: string;
    reason: string;
}): {
    id: Id;
    status: ConsultationStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    diagnosis: string;
    notes: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_ConsultationStatus_n31(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        createdAt: value.createdAt,
        diagnosis: value.diagnosis,
        notes: value.notes,
        reason: value.reason
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    title: string;
    userId: Principal;
    kind: _NotificationKind;
    createdAt: bigint;
    isRead: boolean;
    message: string;
}): {
    id: NotificationId;
    title: string;
    userId: Principal;
    kind: NotificationKind;
    createdAt: bigint;
    isRead: boolean;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        kind: from_candid_NotificationKind_n37(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        isRead: value.isRead,
        message: value.message
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _PrescriptionStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    instructions: string;
    medicines: Array<_Medicine>;
}): {
    id: Id;
    status: PrescriptionStatus;
    doctorId: Principal;
    patientId: Principal;
    date: bigint;
    createdAt: bigint;
    instructions: string;
    medicines: Array<Medicine>;
} {
    return {
        id: value.id,
        status: from_candid_PrescriptionStatus_n41(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        createdAt: value.createdAt,
        instructions: value.instructions,
        medicines: value.medicines
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n45(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n49(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    contact: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    email: [] | [string];
    updatedAt: bigint;
    specialization: string;
    licenseNumber: string;
}): {
    bio?: string;
    contact: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    email?: string;
    updatedAt: bigint;
    specialization: string;
    licenseNumber: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.bio)),
        contact: value.contact,
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.email)),
        updatedAt: value.updatedAt,
        specialization: value.specialization,
        licenseNumber: value.licenseNumber
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    contact: string;
    heightCm: [] | [number];
    userId: Principal;
    name: string;
    createdAt: bigint;
    emergencyContact: [] | [string];
    updatedAt: bigint;
    weightKg: [] | [number];
    bloodGroup: _BloodGroup;
    address: string;
    gender: _Gender;
}): {
    age: bigint;
    contact: string;
    heightCm?: number;
    userId: Principal;
    name: string;
    createdAt: bigint;
    emergencyContact?: string;
    updatedAt: bigint;
    weightKg?: number;
    bloodGroup: BloodGroup;
    address: string;
    gender: Gender;
} {
    return {
        age: value.age,
        contact: value.contact,
        heightCm: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.heightCm)),
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        emergencyContact: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.emergencyContact)),
        updatedAt: value.updatedAt,
        weightKg: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.weightKg)),
        bloodGroup: from_candid_BloodGroup_n58(_uploadFile, _downloadFile, value.bloodGroup),
        address: value.address,
        gender: from_candid_Gender_n60(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DeviceStatus;
    deviceTokenHash: Uint8Array;
    lastSeenAt: [] | [bigint];
    patientId: Principal;
    createdAt: bigint;
    deviceName: string;
    deviceType: string;
}): {
    id: bigint;
    status: DeviceStatus;
    deviceTokenHash: Uint8Array;
    lastSeenAt?: bigint;
    patientId: Principal;
    createdAt: bigint;
    deviceName: string;
    deviceType: string;
} {
    return {
        id: value.id,
        status: from_candid_DeviceStatus_n71(_uploadFile, _downloadFile, value.status),
        deviceTokenHash: value.deviceTokenHash,
        lastSeenAt: record_opt_to_undefined(from_candid_opt_n73(_uploadFile, _downloadFile, value.lastSeenAt)),
        patientId: value.patientId,
        createdAt: value.createdAt,
        deviceName: value.deviceName,
        deviceType: value.deviceType
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sensor: null;
} | {
    manual: null;
}): VitalSource {
    return "sensor" in value ? VitalSource.sensor : "manual" in value ? VitalSource.manual : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    deviceInactive: null;
} | {
    invalidToken: null;
} | {
    deviceNotFound: null;
} | {
    invalidReading: null;
}): VitalsError {
    return "notAuthorized" in value ? VitalsError.notAuthorized : "deviceInactive" in value ? VitalsError.deviceInactive : "invalidToken" in value ? VitalsError.invalidToken : "deviceNotFound" in value ? VitalsError.deviceNotFound : "invalidReading" in value ? VitalsError.invalidReading : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    doctor: null;
}): Role {
    return "patient" in value ? Role.patient : "doctor" in value ? Role.doctor : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): AppointmentStatus {
    return "scheduled" in value ? AppointmentStatus.scheduled : "cancelled" in value ? AppointmentStatus.cancelled : "completed" in value ? AppointmentStatus.completed : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): ConsultationStatus {
    return "closed" in value ? ConsultationStatus.closed : "open" in value ? ConsultationStatus.open : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appointment: null;
} | {
    prescription: null;
} | {
    vital: null;
} | {
    device: null;
} | {
    medicalHistory: null;
} | {
    systemNotification: null;
} | {
    consultation: null;
}): NotificationKind {
    return "appointment" in value ? NotificationKind.appointment : "prescription" in value ? NotificationKind.prescription : "vital" in value ? NotificationKind.vital : "device" in value ? NotificationKind.device : "medicalHistory" in value ? NotificationKind.medicalHistory : "systemNotification" in value ? NotificationKind.systemNotification : "consultation" in value ? NotificationKind.consultation : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): PrescriptionStatus {
    return "active" in value ? PrescriptionStatus.active : "cancelled" in value ? PrescriptionStatus.cancelled : "completed" in value ? PrescriptionStatus.completed : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aNegative: null;
} | {
    oPositive: null;
} | {
    abPositive: null;
} | {
    notSpecified: null;
} | {
    bPositive: null;
} | {
    aPositive: null;
} | {
    oNegative: null;
} | {
    abNegative: null;
} | {
    bNegative: null;
}): BloodGroup {
    return "aNegative" in value ? BloodGroup.aNegative : "oPositive" in value ? BloodGroup.oPositive : "abPositive" in value ? BloodGroup.abPositive : "notSpecified" in value ? BloodGroup.notSpecified : "bPositive" in value ? BloodGroup.bPositive : "aPositive" in value ? BloodGroup.aPositive : "oNegative" in value ? BloodGroup.oNegative : "abNegative" in value ? BloodGroup.abNegative : "bNegative" in value ? BloodGroup.bNegative : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_Device];
} | {
    err: _VitalsError;
}): {
    __kind__: "ok";
    ok: Device | null;
} | {
    __kind__: "err";
    err: VitalsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n68(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_VitalsError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): DeviceStatus {
    return "active" in value ? DeviceStatus.active : "inactive" in value ? DeviceStatus.inactive : value;
}
function from_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_Vital];
} | {
    err: _VitalsError;
}): {
    __kind__: "ok";
    ok: Vital | null;
} | {
    __kind__: "err";
    err: VitalsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n76(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_VitalsError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Vital;
} | {
    err: _VitalsError;
}): {
    __kind__: "ok";
    ok: Vital;
} | {
    __kind__: "err";
    err: VitalsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Vital_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_VitalsError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Vital>;
} | {
    err: _VitalsError;
}): {
    __kind__: "ok";
    ok: Array<Vital>;
} | {
    __kind__: "err";
    err: VitalsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n83(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_VitalsError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Device;
} | {
    err: _VitalsError;
}): {
    __kind__: "ok";
    ok: Device;
} | {
    __kind__: "err";
    err: VitalsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Device_n69(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_VitalsError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vital>): Array<Vital> {
    return value.map((x)=>from_candid_Vital_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Consultation>): Array<Consultation> {
    return value.map((x)=>from_candid_Consultation_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prescription>): Array<Prescription> {
    return value.map((x)=>from_candid_Prescription_n39(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function to_candid_BloodGroup_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
function to_candid_DoctorProfile_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoctorProfile): _DoctorProfile {
    return to_candid_record_n93(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationKind_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationKind): _NotificationKind {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_PatientProfile_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientProfile): _PatientProfile {
    return to_candid_record_n95(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TimeRange_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeRange): _TimeRange {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    contact: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    email?: string;
    updatedAt: bigint;
    specialization: string;
    licenseNumber: string;
}): {
    bio: [] | [string];
    contact: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    email: [] | [string];
    updatedAt: bigint;
    specialization: string;
    licenseNumber: string;
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        contact: value.contact,
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email ? candid_some(value.email) : candid_none(),
        updatedAt: value.updatedAt,
        specialization: value.specialization,
        licenseNumber: value.licenseNumber
    };
}
function to_candid_record_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    contact: string;
    heightCm?: number;
    userId: Principal;
    name: string;
    createdAt: bigint;
    emergencyContact?: string;
    updatedAt: bigint;
    weightKg?: number;
    bloodGroup: BloodGroup;
    address: string;
    gender: Gender;
}): {
    age: bigint;
    contact: string;
    heightCm: [] | [number];
    userId: Principal;
    name: string;
    createdAt: bigint;
    emergencyContact: [] | [string];
    updatedAt: bigint;
    weightKg: [] | [number];
    bloodGroup: _BloodGroup;
    address: string;
    gender: _Gender;
} {
    return {
        age: value.age,
        contact: value.contact,
        heightCm: value.heightCm ? candid_some(value.heightCm) : candid_none(),
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        emergencyContact: value.emergencyContact ? candid_some(value.emergencyContact) : candid_none(),
        updatedAt: value.updatedAt,
        weightKg: value.weightKg ? candid_some(value.weightKg) : candid_none(),
        bloodGroup: to_candid_BloodGroup_n96(_uploadFile, _downloadFile, value.bloodGroup),
        address: value.address,
        gender: to_candid_Gender_n98(_uploadFile, _downloadFile, value.gender)
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    patient: null;
} | {
    doctor: null;
} {
    return value == Role.patient ? {
        patient: null
    } : value == Role.doctor ? {
        doctor: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationKind): {
    appointment: null;
} | {
    prescription: null;
} | {
    vital: null;
} | {
    device: null;
} | {
    medicalHistory: null;
} | {
    systemNotification: null;
} | {
    consultation: null;
} {
    return value == NotificationKind.appointment ? {
        appointment: null
    } : value == NotificationKind.prescription ? {
        prescription: null
    } : value == NotificationKind.vital ? {
        vital: null
    } : value == NotificationKind.device ? {
        device: null
    } : value == NotificationKind.medicalHistory ? {
        medicalHistory: null
    } : value == NotificationKind.systemNotification ? {
        systemNotification: null
    } : value == NotificationKind.consultation ? {
        consultation: null
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeRange): {
    d7: null;
} | {
    m3: null;
} | {
    m6: null;
} | {
    y1: null;
} | {
    d30: null;
} | {
    h24: null;
} {
    return value == TimeRange.d7 ? {
        d7: null
    } : value == TimeRange.m3 ? {
        m3: null
    } : value == TimeRange.m6 ? {
        m6: null
    } : value == TimeRange.y1 ? {
        y1: null
    } : value == TimeRange.d30 ? {
        d30: null
    } : value == TimeRange.h24 ? {
        h24: null
    } : value;
}
function to_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == AppointmentStatus.scheduled ? {
        scheduled: null
    } : value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    aNegative: null;
} | {
    oPositive: null;
} | {
    abPositive: null;
} | {
    notSpecified: null;
} | {
    bPositive: null;
} | {
    aPositive: null;
} | {
    oNegative: null;
} | {
    abNegative: null;
} | {
    bNegative: null;
} {
    return value == BloodGroup.aNegative ? {
        aNegative: null
    } : value == BloodGroup.oPositive ? {
        oPositive: null
    } : value == BloodGroup.abPositive ? {
        abPositive: null
    } : value == BloodGroup.notSpecified ? {
        notSpecified: null
    } : value == BloodGroup.bPositive ? {
        bPositive: null
    } : value == BloodGroup.aPositive ? {
        aPositive: null
    } : value == BloodGroup.oNegative ? {
        oNegative: null
    } : value == BloodGroup.abNegative ? {
        abNegative: null
    } : value == BloodGroup.bNegative ? {
        bNegative: null
    } : value;
}
function to_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
